dist: xenial
language: python
python: 3.7
env:
  global:
  - VERSION=$TRAVIS_TAG
install:
- pip install -r requirements.txt

script:
- python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  user: jondricek
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  password:
    secure: NxBMzuyzWKmh5pS9aGBlv99+s3/HyG4bp7oomlidvSgIeUpsgxpwbr6JPRJ2+8M4CQqeV3/MDAXEwG588UruLpeFqX90MMyNFcUhhkyoq+Jv0ets97/5+v+AFvsxUu9FjZK36DFvRNAngmGnHqCfV8Q/gJD6znNA4VFmoFJ6ZMuneG0EJjnC5/hxWdIVZNTS1urdxuKHBIlxXDV9wD7tNn45nQdT30gWrleEuLcw78p+R3EvhQO3EkYNqC3oDdre6NJ8PEwqIsY5KqZ58/CxD6588a1EbZhDhBR+D8nKjqYQWBAf+szszn8nuCcDeWz1e6DlKnZPj0eYpbImA4AmWJ5ghqh90MKFYNRiQuNXVr+D5EeR4bxYS9b/fDIlg6AollSAm97TdGse13B82LSDeUy63+WEGd5RraxYDMxtahEFP//TFU7cAIrejhChHeiX0EbVA2dIw4EzxsrCL2uUFVm1Lydzby/hTl+SHxHOjQ8BzRKbYCZ6NKmOgo2uIwJazGxmswqriazLybzogAJ/NcNNN/rPi4UIoBTAOCmQCdaq47YIi8u/ypAgn0hao8FixcGZ7gV7gXtR1iapocerVwIIt1N9PBuCxesvud6HFjIYUwztF4A3kUnBGwk+bKiYzSpNNj1Td2jW8keHodW5rGpumbb+vsBDO6lwPsU4H5w=
  on:
    tags: true

